// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDioUGPn0LYO3uSXtNIk0FQBtVXJ1CgQD4',
    appId: '1:529780932146:web:97609b7b35c1fb06d8462b',
    messagingSenderId: '529780932146',
    projectId: 'tmsauth-f1a26',
    authDomain: 'tmsauth-f1a26.firebaseapp.com',
    storageBucket: 'tmsauth-f1a26.firebasestorage.app',
    measurementId: 'G-63ZKY71J30',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC43LzGKf49m-OZzLPtIYb3nN2PLKSBcug',
    appId: '1:529780932146:android:e73174a4f0608915d8462b',
    messagingSenderId: '529780932146',
    projectId: 'tmsauth-f1a26',
    storageBucket: 'tmsauth-f1a26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdvdylK6wHs9U0up82W4vvVKkRjdEEZ4Q',
    appId: '1:529780932146:ios:23ce5a3eb5ed2f22d8462b',
    messagingSenderId: '529780932146',
    projectId: 'tmsauth-f1a26',
    storageBucket: 'tmsauth-f1a26.firebasestorage.app',
    iosBundleId: 'com.example.tms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdvdylK6wHs9U0up82W4vvVKkRjdEEZ4Q',
    appId: '1:529780932146:ios:23ce5a3eb5ed2f22d8462b',
    messagingSenderId: '529780932146',
    projectId: 'tmsauth-f1a26',
    storageBucket: 'tmsauth-f1a26.firebasestorage.app',
    iosBundleId: 'com.example.tms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDioUGPn0LYO3uSXtNIk0FQBtVXJ1CgQD4',
    appId: '1:529780932146:web:53e151a6d9098e25d8462b',
    messagingSenderId: '529780932146',
    projectId: 'tmsauth-f1a26',
    authDomain: 'tmsauth-f1a26.firebaseapp.com',
    storageBucket: 'tmsauth-f1a26.firebasestorage.app',
    measurementId: 'G-GZJ6BK2VF5',
  );
}
